VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Cordillera.dev"
ORG_DBA="Cordillera.dev"
ORG_URL="https://cordillera.dev"
ORG_DESCRIPTION="We provide powerful blockchain services to projects on the Stellar Network. Please be wary of impersonators!"
ORG_TWITTER="CordilleraDev"
ORG_TELEGRAM="@cordilleradev"
ORG_TELEGRAM="@amrithdefiants"
ORG_OFFICIAL_EMAIL="amrith@cordilera.dev"